apiVersion: v1
kind: Service
metadata:
  labels:
    # Enables "zarf connect guac"
    zarf.dev/connect-name: guac
  annotations:
    zarf.dev/connect-description: "Connect to the GUAC Visualizer"
  name: visualizer-connect
  namespace: guac
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/component: visualizer
    app.kubernetes.io/instance: guac
    app.kubernetes.io/name: visualizer
    app.kubernetes.io/part-of: guac
  type: ClusterIP
